version: "3.9"


services:
  scraper:
    build:
      context: .
      dockerfile: Scraper.Dockerfile
    container_name: real-estate-scraper
    restart: always

    volumes:
      - ./logs:/logs
      - ./data:/data

  bot:
    build:
      context: .
      dockerfile: Bot.Dockerfile
    container_name: real-estate-bot
    restart: always

    volumes:
      - ./logs:/logs
      - ./data:/data
